### ISSUE TITLE
Consolidate not listed as a dependency

### ISSUE THREAD

**Issue by irvinebroque** [awesomebox/awesomebox#1]
```
➜  awesomebox-test  awesomebox run            

module.js:340
    throw err;
          ^
Error: Cannot find module 'consolidate'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/lib/view.coffee:8:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/lib/view.coffee:125:4)
    at Module._compile (module.js:449:26)
    at Object.loadFile (/usr/local/lib/node_modules/awesomebox/node_modules/coffee-script/lib/coffee-script/coffee-script.js:179:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/lib/awesomebox.coffee:24:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/lib/awesomebox.coffee:31:4)
    at Module._compile (module.js:449:26)
    at Object.loadFile (/usr/local/lib/node_modules/awesomebox/node_modules/coffee-script/lib/coffee-script/coffee-script.js:179:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/bin/awesomebox-run:4:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)
```

**Comment by mattinsler** [comment]
Oops!!!  Will fix and push up very soon (with partials, which are almost done).

**Comment by mattinsler** [comment]
Fixed.
