### ISSUE TITLE
Error if file is renamed while Awesomebox is running

### ISSUE THREAD

**Issue by irvinebroque** [awesomebox/awesomebox#15]
Let's say I have a file named `foo.html` and I rename it to `bar.html`.

If I then navigate to localhost:8000/bar, I get the following error:

Awesomebox
200 Cannot call method 'slice' of undefined
at Tree.real_relative_path (/usr/local/lib/node_modules/awesomebox/node_modules/awesomebox-core/lib/helpers.coffee:78:40)
at Tree.is_visible (/usr/local/lib/node_modules/awesomebox/node_modules/awesomebox-core/lib/helpers.coffee:69:31)
at Router.respond (/usr/local/lib/node_modules/awesomebox/lib/router.coffee:48:23)
at next (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/proto.js:193:15)
at Object.logger (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/middleware/logger.js:158:5)
at next (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/proto.js:193:15)
at Object.expressInit [as handle](/usr/local/lib/node_modules/awesomebox/node_modules/express/lib/middleware.js:30:5)
at next (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/proto.js:193:15)
at Object.query [as handle](/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
at next (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/proto.js:193:15)
at Function.app.handle (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/proto.js:201:3)
at Server.app (/usr/local/lib/node_modules/awesomebox/node_modules/express/node_modules/connect/lib/connect.js:65:37)
at Server.EventEmitter.emit (events.js:98:17)
at HTTPParser.parser.onIncoming (http.js:2108:12)
at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)
at Socket.socket.ondata (http.js:1966:22)
at TCP.onread (net.js:525:27)

**Comment by irvinebroque** [comment]
This applies to any filename change, including adding a different extension like `.ejs`
