### ISSUE TITLE
Console Error when running two instances of Awesomebox

### ISSUE THREAD

**Issue by irvinebroque** [awesomebox/awesomebox#8]
Getting the following console error - it's not currently causing any problems, but it disappears when I only run one instance of Awesomebox:

TypeError: Cannot call method 'replace' of undefined
    at Mime.lookup (/usr/local/lib/node_modules/awesomebox/node_modules/mime/mime.js:72:18)
    at /usr/local/lib/node_modules/awesomebox/lib/view.coffee:150:17
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/tubing.js:65:15
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/tubing.js:38:13)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/pipe.js:82:22
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at runInDomain (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:125:7)
    at Function.run (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:73:3)
    at trycatch (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:49:19)
    at MethodPipe.process (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/pipe.js:80:7)
    at _fulfilled (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:703:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:732:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:669:13)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:495:49
    at flush (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:106:17)
    at _TOKEN_ (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:171:14)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:187:7
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at runInDomain (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:125:7)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:186:5
    at process._tickDomainCallback (node.js:459:13)
TypeError: Cannot call method 'replace' of undefined
    at Mime.lookup (/usr/local/lib/node_modules/awesomebox/node_modules/mime/mime.js:72:18)
    at /usr/local/lib/node_modules/awesomebox/lib/view.coffee:150:17
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/tubing.js:65:15
    at Object.<anonymous> (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/tubing.js:38:13)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/pipe.js:82:22
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at runInDomain (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:125:7)
    at Function.run (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:73:3)
    at trycatch (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:49:19)
    at MethodPipe.process (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/dist/pipe.js:80:7)
    at _fulfilled (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:703:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:732:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:669:13)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:495:49
    at flush (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/q/q.js:106:17)
    at _TOKEN_ (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:171:14)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:187:7
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at runInDomain (/usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:125:7)
    at /usr/local/lib/node_modules/awesomebox/node_modules/tubing/node_modules/trycatch/lib/trycatch.js:186:5
    at process._tickDomainCallback (node.js:459:13)

**Comment by irvinebroque** [comment]
Got this error while only running one instance of Awesomebox, so that's not the cause.

**Comment by irvinebroque** [comment]
No longer an issue with v0.4.0
